version: '3.4'

services:
  trusec-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DB_CON_STR=${DB_CON_STR}
    networks:
      - trusec-network

networks:
  trusec-network:
    driver: bridge
