name: Deploy Backend to Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: trusecapi.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t trusecapi.azurecr.io/trusec-backend:latest -f TruSec.Backend/Dockerfile TruSec.Backend
        docker push trusecapi.azurecr.io/trusec-backend:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: trusec-api
        slot-name: production
        images: trusecapi.azurecr.io/trusec-backend:latest
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
