name: Deploy Backend to Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.7.0

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: trusecdev.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64 -t trusecdev.azurecr.io/trusec-backend:latest -f TruSec.Backend/Dockerfile TruSec.Backend --push

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: trusec-dev-api
        slot-name: production
        images: trusecdev.azurecr.io/trusec-backend:latest
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
